# exception handling == it is the upnormal condition or error occure during execution time
# a=int(input('enter the number='))
# b=int(input('enter the second number='))
# try: #suspected code
#   div=a/b
#   print(div)
# except:  #code for handling exception
#     print('not given the 0 as second number')


# handling value error
# name error
# try:
#     a=int(input('enter the 1st number='))
#     b=int(input('enter the 2nd number='))
#     c=a/b
#     print(c)
# except ValueError:
#     print('you must enter a number')
# except ZeroDivisionError:
#     print('enter second number not as zero')
# except:
#     print('all other errors handle error')
# else:
#     print('exicuted there is no errors')
# finally:
#     print('always execute')
#
#



